export const sitePage: string;
export const siteMain: string;
export const siteHeader: string;
export const logo: string;
export const siteAside: string;
export const siteFooter: string;
export const example: string;
export const code: string;
export const codeShow: string;
